/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import data.Connect;
import db.CTHoaDonDB;
import db.HoaDonDB;
import db.MenuDB;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import models.Menu;
import process.updateTable;

/**
 *
 * @author Phat Tai
 */
public class jfrStaff extends javax.swing.JFrame {

    /**
     * Creates new form jfrStaff
     */
    public static Connection conn = Connect.getConnection();
    public static String sql = "SELECT id AS N'STT', TenBan AS N'Tên bàn', GhiChu AS N'Ghi chú' FROM Ban";
    public static int idban = 0; // lưu tạm khi ân vào 1 dòng trong bảng phục vụ update và delete
    public int idMenu;
    public int idHoaDon;

    public jfrStaff() {
        initComponents();
        setLocationRelativeTo(null);
        this.lbTenNV.setText("Xin chào " + jfrLogin.tenNV);

        //gọi hàm đổ dữ liệu lên bảng
        updateTable.loadData(sql, tbListTale);
        loadDataCB();
    }

    public void loadDataCB() {
        String sql = "SELECT Ten FROM Menu";
        try {
            PreparedStatement ps = conn.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while (rs.next()) {
                this.cbDrink.addItem(rs.getString("Ten"));
            }
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbTenNV = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbListTale = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbInfo = new javax.swing.JTable();
        btnPay = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtTotalPrice = new javax.swing.JTextField();
        cbDrink = new javax.swing.JComboBox<>();
        spNumber = new javax.swing.JSpinner();
        btnAdd = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Quản ly quán cafe");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lbTenNV.setText("Biến");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Quản lý quán cafe");

        tbListTale.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbListTale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbListTale.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbListTaleMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbListTale);

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnBack.setText("Quay lại");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        tbInfo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tbInfo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bàn số", "Mã hóa đơn", "Tên món", "Số lượng", "Đơn giá", "Thành tiền"
            }
        ));
        tbInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbInfoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbInfo);

        btnPay.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPay.setText("Thanh toán");
        btnPay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnPayMouseClicked(evt);
            }
        });
        btnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPayActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tổng tiền");

        txtTotalPrice.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        txtTotalPrice.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        txtTotalPrice.setText("0");
        txtTotalPrice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTotalPriceActionPerformed(evt);
            }
        });

        cbDrink.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        cbDrink.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbDrinkActionPerformed(evt);
            }
        });

        spNumber.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        spNumber.setModel(new javax.swing.SpinnerNumberModel(1, -100, 100, 1));
        spNumber.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                spNumberAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        btnAdd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnDelete.setText("Xóa");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbDrink, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(spNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbTenNV))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbTenNV)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBack, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPay, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbDrink, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(spNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnAdd)
                            .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        jfrLogin jfr = new jfrLogin();
        this.setVisible(false);
        jfr.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPayActionPerformed

    private void txtTotalPriceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTotalPriceActionPerformed
    }//GEN-LAST:event_txtTotalPriceActionPerformed

    private void tbListTaleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbListTaleMouseClicked
        try {
            String IDrow = (this.tbListTale.getModel().getValueAt(this.tbListTale.getSelectedRow(), 0)).toString();
            String sql1 = "SELECT * FROM Ban WHERE id='" + IDrow + "'";
            ResultSet rs = updateTable.showTextField(sql1);
            if (rs.next()) {
                idban = rs.getInt("id");
            }
            String sql2 = "SELECT Ban.id AS N'Bàn số', HoaDon.id AS N'Mã hóa đơn', Menu.Ten AS N'Tên món',\n"
                    + "SoLuong AS N'Số lượng', Gia N'Đơn giá', Gia*SoLuong AS N'Thành tiền'\n"
                    + "FROM Ban, HoaDon, CT_HoaDon, Menu\n"
                    + "WHERE Ban.id = '" + IDrow + "' AND Ban.id = HoaDon.idBan AND HoaDon.id = CT_HoaDon.idHoaDon\n"
                    + "AND CT_HoaDon.idMenu = Menu.id AND TrangThai = 0";
            updateTable.loadData(sql2, tbInfo);
            try {
                int rowCount = tbInfo.getModel().getRowCount();
                float totalPrice = 0;
                while (rowCount > 0) {
                    String priceInRow = (tbInfo.getModel().getValueAt(rowCount - 1, 5)).toString();
                    float f = Float.parseFloat(priceInRow);
                    totalPrice += f;
                    rowCount--;
                }
                txtTotalPrice.setText(String.valueOf(totalPrice));

            } catch (Exception e) {
            }
        } catch (Exception e) {
            JOptionPane.showInputDialog(null, e);
        }

    }//GEN-LAST:event_tbListTaleMouseClicked

    private void cbDrinkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbDrinkActionPerformed
        idMenu = cbDrink.getSelectedIndex() + 1;
    }//GEN-LAST:event_cbDrinkActionPerformed

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        int countDrink = (int) spNumber.getValue();
        int rowCount = tbInfo.getRowCount();
        try {
            if (idban != 0) {
                //truong hop ban chua co CT_HoaDon
                if (rowCount == 0) {
                    HoaDonDB.insert(idban);
                    idHoaDon = HoaDonDB.maxID();
                    CTHoaDonDB.insert(idHoaDon, idMenu, countDrink);
                    tbListTaleMouseClicked(evt);
                } //truong hop ban da co CT_HoaDon
                else {
                    idHoaDon = (int) tbInfo.getModel().getValueAt(0, 1);

                    //truong hop mon da ton tai => update
                    if (MenuDB.checkDrink(idMenu, idHoaDon)) {
                        CTHoaDonDB.update(countDrink, idHoaDon, idMenu);
                        tbListTaleMouseClicked(evt);
                    } //truong hop mon chua ton tai => insert
                    else {
                        CTHoaDonDB.insert(idHoaDon, idMenu, countDrink);
                        tbListTaleMouseClicked(evt);
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Chưa chọn bàn", "Thông báo", 1);
            }
        } catch (Exception e) {
        }

    }//GEN-LAST:event_btnAddMouseClicked

    private void btnPayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnPayMouseClicked
        if (tbInfo.getModel().getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Bạn chưa chọn bàn hoặc bàn trống", "Thông báo", 2);
        } else if (0 == JOptionPane.showConfirmDialog(null, "Bạn có muốn thanh toán hóa đơn cho bàn " + idban + " không?", "Thoát", 2)) {
            String idHoaDon = tbInfo.getModel().getValueAt(0, 1).toString();
            try {
                HoaDonDB.update(idHoaDon);
                tbListTaleMouseClicked(evt);
            } catch (SQLException ex) {
                Logger.getLogger(jfrStaff.class.getName()).log(Level.SEVERE, null, ex);
            }

        }
    }//GEN-LAST:event_btnPayMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        int idHoaDon = (int) this.tbInfo.getModel().getValueAt(0, 1);
        String tenMon = (this.tbInfo.getModel().getValueAt(this.tbInfo.getSelectedRow(), 2).toString());
        String sql = "DELETE CT_HoaDon WHERE idHoaDon = ? AND idMenu = (SELECT id FROM dbo.Menu WHERE Ten = ?)";
        try {
            PreparedStatement ps = conn.prepareCall(sql);
            ps.setInt(1, idHoaDon);
            ps.setString(2, tenMon);
            ps.execute();

        } catch (SQLException ex) {
            Logger.getLogger(jfrStaff.class.getName()).log(Level.SEVERE, null, ex);
        }
        tbListTaleMouseClicked(evt);
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void tbInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbInfoMouseClicked
    }//GEN-LAST:event_tbInfoMouseClicked

    private void spNumberAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_spNumberAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_spNumberAncestorAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfrStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfrStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfrStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfrStaff.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfrStaff().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnPay;
    private javax.swing.JComboBox<String> cbDrink;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbTenNV;
    private javax.swing.JSpinner spNumber;
    private javax.swing.JTable tbInfo;
    private javax.swing.JTable tbListTale;
    private javax.swing.JTextField txtTotalPrice;
    // End of variables declaration//GEN-END:variables
}
